"""empty message

Revision ID: 5e17af3c352d
Revises: 975dcf4fd8b8
Create Date: 2022-08-28 10:39:01.339411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e17af3c352d'
down_revision = '975dcf4fd8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=32), nullable=False),
    sa.Column('teacher_name', sa.String(length=32), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id')
    )
    op.create_table('students',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('college_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('stu_to_course',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('course_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stu_to_course')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('admins')
    # ### end Alembic commands ###
