"""empty message

Revision ID: b1c504b66fc9
Revises: 
Create Date: 2022-08-19 16:51:16.292027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c504b66fc9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=32), nullable=False),
    sa.Column('teacher_name', sa.String(length=32), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('students',
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('class_name', sa.String(length=32), nullable=False),
    sa.Column('college_name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('student_id')
    )
    op.create_table('stu_to_course',
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('course_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], ),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stu_to_course')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('admins')
    # ### end Alembic commands ###
