FROM python:3.9.5-slim-buster
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

ENV nameko_username=root nameko_password=root rabbitmq_host=rabbitmq
COPY . /usr/src/app/

CMD sh -c "nameko run services_student --broker amqp://$nameko_username:$nameko_password@$rabbitmq_host"